name: sprockets-commoner

type: ruby

up:
  - ruby: 2.5.0
  - node:
      version: v8.12.0
      yarn: 1.12.3
  - custom:
      name: Install
      met?: bin/setup
      meet: 'false'

commands:
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/test
