source 'https://rubygems.org'

gem 'coffee-script'
gem 'rails', '4.2.6'
gem 'sprockets-commoner', path: '../../'
gem 'sprockets', github: 'rails/sprockets'

group :development, :test do
  gem 'teaspoon'
  gem 'teaspoon-bundle'
  gem 'teaspoon-jasmine'
end
